#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

if ! command -v nginx &>/dev/null; then
        sudo apt-get update
        sudo apt-get install -y nginx
fi

if ! sudo ufw status | grep -q "80"; then
        sudo ufw allow "nginx http"
fi
sudo chmod 755 /var/www/html
sudo chmod -R 755 /var/www
echo "Hello world!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

default_config="
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Add custom header
        add_header X-Served-By \$hostname;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
                rewrite ^/redirect_me(.*)\$ https://www.youtube.com/watch?v=70JD5YTemJc permanent;
        }

        error_page 404 /custom_404.html;
        location = /custom_404.html {
                internal;
        }
#       location ~ /redirect_me {
#               return 301 https://www.example.com/;
#       }
}
"
echo "$default_config" | sudo tee /etc/nginx/sites-available/default >/dev/null

if [ "$(pgrep -c nginx)" -le 0 ]; then
        sudo service nginx start
else
        sudo service nginx restart
fi
