#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Update system packages

sudo apt-get update -y
sudo apt-get upgrade -y

# Install HAProxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get -y install haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo touch /etc/haproxy/haproxy.cfg

echo '
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server 197657-web-01 54.144.147.16:80 check
    server 197657-web-02 35.153.79.189:80 check
' | sudo tee /etc/haproxy/haproxy.cfg >/dev/null

if ! sudo haproxy -c -f /etc/haproxy/haproxy.cfg | grep -w "valid"; then
        echo "Configuration file is not valid"
        exit 1
fi

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
