#!/usr/bin/env bash
# Bash script to make Nginx be run, and listenon port 80 of all the server’s active IPv4 IPs
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"

