#!/usr/bin/env bash
# Bash script to make Nginx be run, and listenon port 80 of all the server’s active IPv4 IPs: make your fix short and sweet
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo service nginx restart
