#!/usr/bin/env bash
# Bash script to make Nginx be run, and listenon port 80 of all the server’s active IPv4 IPs: make your fix short and sweet
sudo apt-get update
sudo apt-get install -y puppet
sudo puppet apply nginx_debug.pp