#!/usr/bin/env bash
#manages manage_my_process

prog="manage_my_process"

#start function
start()
{
       ./manage_my_process &
       echo "$!" > /var/run/my_process.pid
       echo "$prog started"
}

#stop function
stop ()
{
	kill "$(cat /var/run/my_process.pid)"
	rm  -f /var/run/my_process.pid
	echo "$prog stopped"
}

#restart function
restart ()
{
	kill "$(cat /var/run/my_process.pid)"
        rm  -f /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "$prog restarted"
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
