#!/usr/bin/env bash
#manages manage_my_process

prog="manage_my_process"
path_file="/root/alx-system_engineering-devops/0x05-processes_and_signals/manage_my_process"
pid_file="/var/run/my_process.pid"

#start function
start()
{
	"$path_file" &
	echo "$!" > "$pid_file"
	echo "$prog started"
}

#stop function
stop ()
{
	kill -9 "$(cat "$pid_file")"
	rm  -f "$pid_file"
	echo "$prog stopped"
}

#restart function
restart ()
{
	kill -9 "$(cat "$pid_file")"
        rm  -f "$pid_file"
	"$path_file" &
	echo "$!" > "$pid_file"
	echo "$prog restarted"
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
