#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.

LOG_FILE="/var/log/apache2/access.log"
awk '{print $1, $9}' $LOG_FILE | sort | uniq -c | sort -nr
