#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first
#+dash is displayed (refer to the example)

for i in *
do
	if [[ $i == *-* ]]
	then
		echo "${i#*-}"
	else
		echo "$i"
	fi
done
