#!/usr/bin/env bash
# configures a container to nginx to run as nginx user and listen to port 8080
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
